# Matrix

## Intro

In [1]:
import numpy as np

Vector

In [3]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [4]:
vector.shape

(3,)

Matrix

In [10]:
matrix = np.array(
                [[1,2],
                [3,4],
                [5,6]]
                )
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
matrix.shape

(3, 2)

## Square Matrix

In [11]:
A = np.array(
                [[1,2,3],
                [4,5,6],
                [7,8,9]]
                )
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
A[1]

array([4, 5, 6])

In [13]:
A[1][2]

6

In [14]:
A[1, 2]

6

In [15]:
A[:,-1]

array([3, 6, 9])

## Upper Triangle Matrix

In [16]:
np.triu(A)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

## Lower Triangle Matrix

In [17]:
np.tril(A)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

## Diagonal Matrix

In [18]:
np.diag(A)

array([1, 5, 9])

### Identity Matrix

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
mat_ident = np.identity(3)
mat_ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
A @ mat_ident

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## Arithmetic

### Addition/Substraction

Sama seperti vektor

### Division

Sama seperti vektor

### Multiplication

#### Scalar

Sama seperti vektor

#### Hadamard Product

In [38]:
B = np.array(
    [[1,8,2],
    [2,1,1],
    [1,2,1]]
)
B

array([[1, 8, 2],
       [2, 1, 1],
       [1, 2, 1]])

In [40]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
A * B

array([[ 1, 16,  6],
       [ 8,  5,  6],
       [ 7, 16,  9]])

#### Matrix - Matrix

Jumlah kolom di matrix pertama harus sama dengan baris di matriks kedua

In [30]:
C = np.array(
    [[1,2],
    [3,4],
    [5,6]]
)
C

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
D = np.array(
    [[7,8],
    [9,10]]
)
D

array([[ 7,  8],
       [ 9, 10]])

In [41]:
np.dot(C,D)

array([[ 25,  28],
       [ 57,  64],
       [ 89, 100]])

In [42]:
C @ D

array([[ 25,  28],
       [ 57,  64],
       [ 89, 100]])

In [44]:
C.dot(D)

array([[ 25,  28],
       [ 57,  64],
       [ 89, 100]])

In [47]:
vector

array([1, 2, 3])

In [48]:
C

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
C.shape

(3, 2)

In [57]:
C = C.T
C.shape

(2, 3)

In [49]:
vector.shape

(3,)

In [55]:
vector = np.expand_dims(vector,axis=1)

In [56]:
vector.shape

(3, 1)

In [59]:
C@vector

array([[22],
       [28]])

## Inverse

Cek determinan

In [28]:
np.linalg.det(A)

0.0

Karena 0, maka inverse-nya tidak ada

In [26]:
mat_invers = np.linalg.inv(A)
mat_invers

LinAlgError: Singular matrix

Invers

A^-1 = 1/det * A_adj

Matriks singular:

1. barisnya merupakan kelipatan
2. kombinasi linier dari baris

123

246 -> kelipatan 2 dari baris pertama

---
123

456 -> tambah 3 dari baris pertama

Perhitungan manual invers

A = 

a b

c d

A_adj =

d -b

-c a

det = ad - cb

In [63]:
1 * 4 - (2 * 3)

-2

In [62]:
F = np.array(
    [[1,2],
    [3,4]]
)
F

array([[1, 2],
       [3, 4]])

In [64]:
np.linalg.det(F)

-2.0000000000000004

In [61]:
F_adj = np.array(
    [[4,-2],
    [-3,1]]
)
F_adj

array([[ 4, -2],
       [-3,  1]])

In [65]:
np.linalg.inv(F)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])