In [1]:
import numpy as np

1. Apakah [1,3] adalah eigenvector dari [[1,-1],[6,4]]? Jika iya, berapakah eigenvalue-nya?

In [2]:
A = np.array([
    [1,-1],
    [6,4]
])
A

array([[ 1, -1],
       [ 6,  4]])

In [11]:
v = np.array([1,3])
v

array([1, 3])

In [14]:
C = A@v
C

array([-2, 18])

In [15]:
C/v

array([-2.,  6.])

Bukan skalar, v bukan eigenvector