In [1]:
import numpy as np

1. Buat tensor

In [3]:
tensor = np.array([[[[23,50],[7,12]],[[57,67],[99,43]]],
[[[75,21],[57,12]],[[87,26],[18,84]]]])
tensor

array([[[[23, 50],
         [ 7, 12]],

        [[57, 67],
         [99, 43]]],


       [[[75, 21],
         [57, 12]],

        [[87, 26],
         [18, 84]]]])

2. Perkalian matrix

In [4]:
A = np.array([
    [23,50,19],
    [7,12,109],
    [57,67,98]
])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [6]:
B = np.array([
    [17],
    [22],
    [19]
])
B

array([[17],
       [22],
       [19]])

Dot product

In [7]:
A @ B

array([[1852],
       [2454],
       [4305]])

Hadamard product

In [8]:
A*B

array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

3. Transpose, determinant, inverse

In [12]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

A Transpose

In [11]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

A Determinant

In [13]:
np.linalg.det(A)

131344.0000000002

A Inverse

In [14]:
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])