Numpy

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,4])
a

array([1, 2, 4])

In [6]:
tinggi = [1.7, 1.8, 2.0]
berat = [65.5, 67.2, 59.2]
np_tinggi = np.array(tinggi)
np_berat = np.array(berat)

#berat/tinggi akan error kalau belum jadi np.array
print(np_berat/np_tinggi)
print(np.around(np_berat/np_tinggi,decimals=2))
print(np.round(np_berat/np_tinggi,2))


[38.52941176 37.33333333 29.6       ]
[38.53 37.33 29.6 ]
[38.53 37.33 29.6 ]


Range

In [7]:
ar = np.arange(3)
pr = list(range(1,4,1))
arr = np.append(ar,np.flip(ar))
print(arr)
arr

[0 1 2 2 1 0]


array([0, 1, 2, 2, 1, 0])

In [8]:
np.sort(arr)
np.flip(np.sort(arr))

array([2, 2, 1, 1, 0, 0])

Skalar - 0 Dimensi

In [9]:
zerodim = np.array(4)
print(zerodim)
print(zerodim.shape)
print(zerodim.ndim)
zerodim.size

4
()
0


1

Vektor - 1 Dimensi

In [10]:
onedim = ar.copy()
print(onedim)
print(onedim.shape)
print(onedim.ndim)
onedim.size

[0 1 2]
(3,)
1


3

Matriks - 2 Dimensi

In [11]:
twodim = np.array([[ar],[ar]])
print(twodim)
print(twodim.shape)
print(twodim.ndim)
twodim.size

[[[0 1 2]]

 [[0 1 2]]]
(2, 1, 3)
3


6

3 Dimensi -> 332 -> 3 baris terluar -> 3 baris di dalam -> 2 elemen di dalam

In [12]:
threedim = np.array([[1,1],[1,1],[1,1],[2,2],[2,2],[2,2],[3,3],[3,3],[3,3]])
print(threedim)
#threedim = threedim.reshape(3,2,3)
#print(threedim)
#print(threedim.shape)
#print(threedim.ndim)

[[1 1]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [3 3]
 [3 3]]


In [13]:
threedim332 = threedim.reshape(3,3,2)
print(threedim332)
print(threedim332.shape)
print(threedim332.ndim)
threedim332.size

[[[1 1]
  [1 1]
  [1 1]]

 [[2 2]
  [2 2]
  [2 2]]

 [[3 3]
  [3 3]
  [3 3]]]
(3, 3, 2)
3


18

In [14]:
threedim323 = threedim.reshape(3,2,3)
print(threedim323)
print(threedim323.shape)
print(threedim323.ndim)

[[[1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]]

 [[3 3 3]
  [3 3 3]]]
(3, 2, 3)
3


In [15]:
threedim233 = threedim.reshape(2,3,3)
print(threedim233)
print(threedim233.shape)
print(threedim233.ndim)

[[[1 1 1]
  [1 1 1]
  [2 2 2]]

 [[2 2 2]
  [3 3 3]
  [3 3 3]]]
(2, 3, 3)
3


Reshape

In [16]:
c = np.arange(6)
print(c)

[0 1 2 3 4 5]


In [17]:
matriks32 = c.reshape(3,2)
print(f'matriks 3x2: \n{matriks32}')

matriks23 = c.reshape(2,3)
print(f'matriks 2x3: \n{matriks23}')


matriks 3x2: 
[[0 1]
 [2 3]
 [4 5]]
matriks 2x3: 
[[0 1 2]
 [3 4 5]]


In [18]:
newvec = np.arange(0,12,1)
print(newvec.reshape(4,3,1))
newvec.reshape(1,1,12)

[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]]


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]])

Expand Row vs Column

In [19]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [20]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


Row

In [21]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

print(a.reshape(2,3))

(1, 6)
[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]


Column

In [22]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [23]:
a = np.array([1, 2, 3, 4, 5, 6])
b=np.arange(7,13,1)
ab = np.append(a,b)
#abc = ab.reshape(2,2,3)
print(ab)
d=np.expand_dims(ab,axis=0)
print(d.shape[0])
print(d.shape)
e=np.expand_dims(ab,axis=1)
print('d\n',d,'\n',np.shape(d))
print('e\n',e,'\n',np.shape(e))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(1, 12)
d
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]] 
 (1, 12)
e
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] 
 (12, 1)


Bacaan lanjutan Axis
https://www.sharpsightlabs.com/blog/numpy-axes-explained/

Expand n_dims

In [24]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
print(a)

[1 2 3 4 5 6]


In [25]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [26]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape
print(c)

[[1 2 3 4 5 6]]


Latihan

In [27]:
arr = np.array([2,3,7,8,9])
print(arr[2:5:3]) # -> 3 sebagai step
print(arr[::2])
print(arr[2:5:1])

[7]
[2 7 9]
[7 8 9]


In [28]:
arr = np.array([[2,3,7,8,9],[1,3,6,8]]) #-> error karena dimensinya ga sama di row kedua kurang 1 elemen
print(arr[1,1:3])

C:\Users\Judan Syamsul Hadad\AppData\Local\Temp\ipykernel_16092\1517445769.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[2,3,7,8,9],[1,3,6,8]]) #-> error karena dimensinya ga sama di row kedua kurang 1 elemen


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
arr = np.array([[2,3,7,8,9],[1,3,6,8,7]]) #-> ga error karena dimensinya sama
print(arr[1,1:3])

[3 6]


In [ ]:
print(arr[0:2,2]) #ngambil semua 23789 sama 13689, baru ambil elemen ke-1 (2-1)

[7 6]


In [ ]:
print(arr[1:4])
print(arr[1:3]) #sama dengan atas karena isinya cuma dua row, ke-0 dan ke-1

print(arr[0:3]) #kepanggil 2-2nya

#yang diambil row aja, kalau mau dalamnya harus arr[0:2,x] dengan x elemen yang mau diambil, misal
print('*',arr)
print(arr[0:2,0])
print(arr[0:2,0:3])
print(arr[0:2,0:4:2])

[[1 3 6 8 7]]
[[1 3 6 8 7]]
[[2 3 7 8 9]
 [1 3 6 8 7]]
* [[2 3 7 8 9]
 [1 3 6 8 7]]
[2 1]
[[2 3 7]
 [1 3 6]]
[[2 7]
 [1 6]]


vstack hstack

In [ ]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
print(a1,'\n*')
print(a2)

[[1 1]
 [2 2]] 
*
[[3 3]
 [4 4]]


In [ ]:
print(np.hstack((a1,a2)),'\n*')
print(np.vstack((a1,a2)),'\n*')

[[1 1 3 3]
 [2 2 4 4]] 
*
[[1 1]
 [2 2]
 [3 3]
 [4 4]] 
*


unknown dim

In [ ]:
new_arr = np.hstack((a1,a2))
new_arr = np.vstack((new_arr,new_arr))
print(new_arr)
new_arr3d = new_arr.reshape(2,2,-1) #otomatis -1 jadi 4 elemen
print('\n*',new_arr3d)

[[1 1 3 3]
 [2 2 4 4]
 [1 1 3 3]
 [2 2 4 4]]

* [[[1 1 3 3]
  [2 2 4 4]]

 [[1 1 3 3]
  [2 2 4 4]]]


Latihan

In [ ]:
def convert(fahr):
    cels = fahr * 1.8 + 32.0

print(convert(32))

None


In [ ]:
def convert(fahr,kelv):
    cels = fahr * 1.8 + 32.0
    cels2 = kelv - 273,15
    return cels, cels2
print("Temperature in celsius (C) = ",convert(32,20))
ctemp = convert(32,20)
ctemp[0]
ctemp[1]
ctemp[1]

Temperature in celsius (C) =  (89.6, (-253, 15))


(-253, 15)

In [ ]:
def temp_converter(ftemp):
    ctemp = (ftemp-32)*(5/9)
    ktemp = ctemp + 273.15
    return[ftemp,ktemp,ctemp]

print(temp_converter(72))

[72, 295.3722222222222, 22.22222222222222]


list

In [ ]:
def fahr_to_celsius(temp):
    return (temp-32) * (5/9)

print(fahr_to_celsius(72))

22.22222222222222


In [ ]:
def myfunc():
    st='jojon'
    y=35
    return st,y

#(myfunc()[0])
a,b = myfunc()
print(a)
c = myfunc()
print(c[0])

jojon
jojon


SUM AXIS

In [35]:
arrsum = np.array([[1,1],[2,2]])
sum_ke_bawah = np.sum(arrsum, axis=0) #axis = 0 ke bawah
sum_ke_samping = np.sum(arrsum, axis=1) #axis = 1 ke samping
print(sum_ke_bawah)
print(sum_ke_samping)

[3 3]
[2 4]


MAX

In [51]:
maxarrsum = sum_ke_bawah + sum_ke_samping
vstarrsum = np.vstack((arrsum,sum_ke_bawah,maxarrsum))
print(vstarrsum)
print(np.max(vstarrsum))
print(np.max(vstarrsum,axis=0))
print(np.max(vstarrsum,axis=1))

[[1 1]
 [2 2]
 [3 3]
 [5 7]]
7
[5 7]
[1 2 3 7]
[[1 2 3 5]
 [1 2 3 7]]


TRANSPOSE

In [52]:
print(vstarrsum.T)

[[1 2 3 5]
 [1 2 3 7]]


FLATTEN

In [53]:
vstarrflat = vstarrsum.flatten()
print(vstarrflat)

[1 1 2 2 3 3 5 7]
